#line 2 "lex.yy.cc"

#line 4 "lex.yy.cc"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

#define YY_FLEX_LEX_COMPAT
extern int yylineno;
int yylineno = 1;

extern char yytext[];

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	if ( yyleng >= YYLMAX ) \
		YY_FATAL_ERROR( "token too large, exceeds YYLMAX" ); \
	yy_flex_strncpy( yytext, (yytext_ptr), yyleng + 1 ); \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 18
#define YY_END_OF_BUFFER 19
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[225] =
    {   0,
        0,    0,   19,   17,    2,    1,   17,   18,    3,   17,
        9,    4,   12,   17,   10,   16,   17,   17,    0,   12,
       17,    0,   11,   17,    0,   12,    0,    0,   12,    0,
        7,    6,    5,   12,   12,   12,   12,   17,   16,   16,
       16,   12,   17,   11,   17,   11,    0,   12,   12,   11,
       12,   12,   12,    0,    0,    0,   13,   12,   12,   12,
        0,    0,   12,    8,   12,   17,   16,   12,   12,   12,
       17,   17,   12,   17,   11,   17,   12,    0,   11,   12,
       12,   12,   13,    0,   12,   12,   12,   12,   12,   15,
       12,   12,   12,   12,   12,   12,   12,   17,   16,   16,

       12,   12,   15,   12,   15,   12,   11,   12,   12,   12,
        0,   11,    0,   12,   12,    0,    0,   13,   12,   12,
       15,   15,   15,   12,   15,   12,   12,   12,   12,   12,
       17,   15,   12,   12,   12,   12,   15,   15,   12,   15,
       12,   12,   12,   12,   15,   11,   15,   15,   12,   15,
       12,   11,   12,   12,   12,   12,   15,   12,   11,   12,
       12,   12,   15,   12,   12,   12,   12,   12,   15,   12,
       12,   12,   17,   15,   15,   12,   15,   12,   12,   12,
       12,   11,   15,   12,   11,   12,   12,   15,   11,   15,
       12,   15,   12,   11,   12,   12,   12,   15,   15,   15,

       13,   12,   15,   12,   12,   12,   12,   12,   12,   15,
       12,   14,   15,   12,   15,   13,   12,   12,   12,   12,
       14,   15,   12,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    5,    1,    6,    1,    7,    1,    8,
        9,    1,    1,    1,    1,    1,   10,    1,    1,   11,
        1,    1,    1,    1,    1,    1,    1,    1,    1,   12,
        1,   13,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,   14,    1,    1,    1,    1,    1,    1,   15,    1,

       16,    1,    1,    1,    1,    1,    1,    1,    1,    1,
       17,    1,    1,   18,   19,    1,   20,    1,    1,    1,
        1,    1,   21,   22,   23,   24,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[25] =
    {   0,
        1,    2,    3,    4,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[261] =
    {   0,
        0,  180,  201,   19, 1416, 1416,   38,   55,   21,   71,
       22,   88,   97,   17,   23,  114,  187,   25,   33,  131,
      150,  194,    0,  177,  169,  180,   34,  199,   43,  208,
       48,   50,   52,    0,  176,   59,    0,   54,  225,  175,
        0,  242,  259,  190,  278,  297,  308,  326,  337,    0,
      170,  356,    0,  367,  181,  378,  168,  396,   65,   66,
      405,    0,  423,   75,  441,   57,  458,  475,  167,    0,
      492,    0,  510,  530,    0,    0,  553,  574,  593,  604,
      161,  158,  171,  622,  641,  652,  158,  157,  668,  685,
      154,  153,  148,  703,    0,    0,    0,   75,  721,    0,

      739,  757,  774,  792,  815,    0,    0,    0,    0,  839,
      860,    0,    0,  883,  147,  904,    0,    0,  927,  146,
      946,    0,   85,  964,    0,    0,    0,   86,    0,    0,
       92,  982,  145,  144,  143, 1000, 1018,    0, 1036,    0,
        0,    0,    0,    0,    0,    0,    0, 1056,    0,    0,
        0,    0,    0, 1067,    0,    0, 1081,    0,    0,    0,
        0, 1105, 1129,    0,    0,    0,    0, 1153,   92,  101,
      108,  111,   83, 1172,    0, 1190,    0,    0,    0,    0,
        0, 1210, 1221, 1239, 1250, 1261,  144,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0, 1279,

        0,    0,    0,    0,    0, 1290,    0,    0,    0,  138,
      137,    0,  136,  135, 1301,  131, 1319, 1330,  130,  129,
        0,  126,  125, 1416,  146, 1351,  145,  141,  140, 1355,
     1359, 1363, 1367,  139,  138,  134,  133, 1371, 1375, 1379,
     1383,  132,  131,  130, 1387, 1391,  129,  122,  117,  115,
      111,   96,   81,   67,   52, 1395, 1399, 1403, 1407, 1411
    } ;

static const flex_int16_t yy_def[261] =
    {   0,
      224,    1,  224,  225,  224,  224,  226,  227,  227,  225,
      227,  227,  228,   10,  227,  229,   10,   10,  227,  228,
      226,  230,   21,   21,  231,  232,  227,  233,  234,  235,
      227,  227,  227,   20,   20,  234,   20,   10,  229,   39,
       39,  236,  237,  230,  238,  231,  231,  239,  232,   49,
       49,  239,   49,  233,  240,  233,   56,  241,  234,  234,
      235,   61,  242,  227,  243,   10,  244,  236,   68,   68,
      237,   71,  243,  238,   74,   74,  224,  245,  239,  239,
       80,   77,  240,  246,  241,  241,   86,   86,  242,  247,
       89,   89,   89,  248,   73,   73,   73,   10,  244,   99,

      249,  249,  250,  251,  224,   77,   77,   77,   77,  224,
      245,  111,  111,  224,  114,  246,  116,  116,  224,  119,
      247,  121,  252,  248,  121,  124,  124,  253,  124,  124,
       10,  254,  102,  102,  102,  255,  250,  137,  251,  137,
      139,  139,  139,  139,  105,  105,  105,  256,  110,  105,
      110,  110,  110,  257,  110,  110,  224,  114,  114,  114,
      114,  224,  224,  119,  119,  119,  119,  224,  252,  253,
      253,  253,   10,  254,  174,  255,  174,  176,  176,  176,
      176,  256,  256,  257,  257,  257,  186,  157,  157,  157,
      162,  157,  162,  162,  162,  162,  162,  163,  163,  258,

      163,  168,  163,  168,  168,  259,  168,  168,  168,  121,
      124,  260,  157,  162,  258,  215,  259,  259,  218,  218,
      260,  163,  168,    0,  224,  224,  224,  224,  224,  224,
      224,  224,  224,  224,  224,  224,  224,  224,  224,  224,
      224,  224,  224,  224,  224,  224,  224,  224,  224,  224,
      224,  224,  224,  224,  224,  224,  224,  224,  224,  224
    } ;

static const flex_int16_t yy_nxt[1441] =
    {   0,
        4,    5,    6,    5,    7,    8,    9,    4,    4,    4,
       10,   11,   12,   13,    4,    4,    4,    4,   14,    4,
        4,   15,    4,    4,   18,   19,   27,   27,   27,   19,
       19,   19,   20,   38,   29,   29,   29,   19,   27,   27,
       19,   22,   23,   24,   25,   43,   29,   29,   59,   25,
       25,   26,  178,   27,   30,   27,   60,   27,   64,   25,
       27,   29,   28,   29,   59,   29,   19,  174,   29,   19,
       59,   59,   60,   66,   98,   30,   18,   19,   60,   60,
       27,  128,   19,   31,   20,   89,  212,   19,   29,  131,
      169,  171,   19,   27,   32,   19,  123,  169,  170,  172,

       33,   29,   35,   36,   19,  170,  171,  173,   36,   36,
       37,  141,  210,  171,  172,  137,  171,  133,   36,   40,
       19,  172,  126,   41,  172,   19,   19,   42,  211,  121,
       99,   95,   91,   71,   68,   19,   35,   36,   61,   36,
       39,   34,   36,   36,   37,   19,   17,  204,  198,  206,
      206,  200,   36,   22,   23,   24,   25,  193,  188,  126,
      121,   25,   25,   26,  154,  136,  136,  136,  164,  158,
       94,   25,   22,   46,   47,   94,   94,   85,   85,   83,
      106,   52,   48,   22,   50,   51,   52,  102,   54,   83,
       82,   52,   52,   53,   44,   67,   65,   45,   44,   19,

      224,   52,   55,   16,   56,  224,  224,   57,  224,  224,
      224,  224,   58,   62,   19,  224,  224,  224,  224,   19,
       19,   63,  224,  224,  224,  224,  224,  224,  224,   19,
       40,   19,  224,  224,  224,  224,   19,   19,   42,  224,
      224,  224,  224,  224,  224,  224,   19,   69,   36,  224,
      224,  224,  224,   36,   36,   70,  224,  224,  224,  224,
      224,  224,  224,   36,   72,   19,  224,  224,  224,  224,
       19,   19,   73,  224,  224,  224,  224,  224,  224,  224,
       19,   22,   75,   76,   25,  224,  224,  224,  224,   25,
       25,   77,  224,  224,  224,  224,  224,  224,  224,   25,

       22,   46,   47,  224,  224,  224,  224,  224,  224,  224,
       48,   22,   46,   47,  224,  224,  224,  224,  224,  224,
      224,   48,  224,  224,  224,  224,  224,  224,   78,   22,
       79,   80,  224,  224,  224,  224,  224,  224,  224,   81,
       22,   50,   51,   52,  224,  224,  224,  224,   52,   52,
       53,  224,  224,  224,  224,  224,  224,  224,   52,   22,
       79,   80,  224,  224,  224,  224,  224,  224,  224,   81,
       55,  224,   56,  224,  224,   57,  224,  224,  224,  224,
       58,   55,  224,   56,  224,  224,   57,  224,  224,  224,
      224,   58,  224,  224,  224,  224,  224,  224,   84,   55,

      224,   86,  224,  224,   87,  224,  224,  224,  224,   88,
       62,   19,  224,  224,  224,  224,   19,   19,   63,  224,
      224,  224,  224,  224,  224,  224,   19,   90,   92,   36,
      224,  224,  224,  224,   36,   36,   93,  224,  224,  224,
      224,  224,  224,  224,   36,   94,   96,   36,  224,  224,
      224,  224,   36,   36,   97,  224,  224,  224,  224,  224,
      224,  224,   36,  100,   19,  224,  224,  224,  224,   19,
       19,  101,  224,  224,  224,  224,  224,  224,  224,   19,
       69,   36,  224,  224,  224,  224,   36,   36,   70,  224,
      224,  224,  224,  224,  224,  224,   36,   72,   19,  224,

      224,  224,  224,   19,   19,   73,  224,  224,  224,  224,
      224,  224,  224,   19,  103,   96,   36,  224,  224,  224,
      224,   36,   36,   97,  224,  224,  224,  224,  224,  224,
      224,   36,  104,   22,   75,   76,   25,  224,  224,  224,
      224,   25,   25,   77,  224,  224,  224,  224,  224,  224,
      224,   25,  105,  106,  224,  224,   22,  107,  108,   52,
      106,  106,  106,  106,   52,   52,  109,  106,  106,  106,
      106,  106,  106,  106,   52,  110,  106,   22,  112,  113,
       25,  224,  224,  224,  224,   25,   25,  114,  224,  224,
      224,  224,  224,  224,  224,   25,   22,   79,   80,  224,

      224,  224,  224,  224,  224,  224,   81,   22,   79,   80,
      224,  224,  224,  224,  224,  224,  224,   81,  224,  224,
      224,  224,  224,  224,  115,   55,  224,  117,   54,  224,
      118,  224,  224,   54,   54,  119,  224,  224,  224,  224,
      224,  224,  224,   54,   55,  224,   86,  224,  224,   87,
      224,  224,  224,  224,   88,   55,  224,   86,  224,  224,
       87,  224,  224,  224,  224,   88,  224,  224,  224,  224,
      224,  224,  120,   92,   36,  224,  224,  224,  224,   36,
       36,   93,  224,  224,  224,  224,  224,  224,  224,   36,
      122,  123,  224,  224,  224,  224,  123,  123,  124,  224,

      224,  224,  224,  224,  224,  224,  123,  125,  127,  128,
      224,  224,  224,  224,  128,  128,  129,  224,  224,  224,
      224,  224,  224,  224,  128,  130,  100,   19,  224,  224,
      224,  224,   19,   19,  101,  224,  224,  224,  224,  224,
      224,  224,   19,  132,  134,   36,  224,  224,  224,  224,
       36,   36,  135,  224,  224,  224,  224,  224,  224,  224,
       36,  136,  134,   36,  224,  224,  224,  224,   36,   36,
      135,  224,  224,  224,  224,  224,  224,  224,   36,  138,
      123,  224,  224,  224,  224,  123,  123,  139,  224,  224,
      224,  224,  224,  224,  224,  123,  140,  142,  128,  224,

      224,  224,  224,  128,  128,  143,  224,  224,  224,  224,
      224,  224,  224,  128,  144,  145,  224,  224,   22,  146,
      147,  148,  145,  145,  145,  145,  148,  148,  149,  145,
      145,  145,  145,  145,  145,  145,  148,  150,  145,  151,
      224,  224,   22,  152,  153,  154,  151,  151,  151,  151,
      154,  154,  155,  151,  151,  151,  151,  151,  151,  151,
      154,  156,  151,   22,  112,  113,   25,  224,  224,  224,
      224,   25,   25,  114,  224,  224,  224,  224,  224,  224,
      224,   25,  157,  158,  224,  224,   22,  159,  160,   52,
      158,  158,  158,  158,   52,   52,  161,  158,  158,  158,

      158,  158,  158,  158,   52,  162,  158,   55,  224,  117,
       54,  224,  118,  224,  224,   54,   54,  119,  224,  224,
      224,  224,  224,  224,  224,   54,  163,  164,  224,  224,
       55,  164,  165,   85,  164,  166,  164,  164,   85,   85,
      167,  164,  164,  164,  164,  164,  164,  164,   85,  168,
      164,  122,  123,  224,  224,  224,  224,  123,  123,  124,
      224,  224,  224,  224,  224,  224,  224,  123,  125,  127,
      128,  224,  224,  224,  224,  128,  128,  129,  224,  224,
      224,  224,  224,  224,  224,  128,  130,  175,  123,  224,
      224,  224,  224,  123,  123,  176,  224,  224,  224,  224,

      224,  224,  224,  123,  177,  179,  128,  224,  224,  224,
      224,  128,  128,  180,  224,  224,  224,  224,  224,  224,
      224,  128,  181,  138,  123,  224,  224,  224,  224,  123,
      123,  139,  224,  224,  224,  224,  224,  224,  224,  123,
      140,  142,  128,  224,  224,  224,  224,  128,  128,  143,
      224,  224,  224,  224,  224,  224,  224,  128,  144,   22,
      182,  183,  224,  224,  224,  224,  224,  224,  224,  184,
       22,  185,  186,  224,  224,  224,  224,  224,  224,  224,
      187,  188,  224,  224,   22,  189,  190,  148,  188,  188,
      188,  188,  148,  148,  191,  188,  188,  188,  188,  188,

      188,  188,  148,  192,  188,  193,  224,  224,   22,  194,
      195,  154,  193,  193,  193,  193,  154,  154,  196,  193,
      193,  193,  193,  193,  193,  193,  154,  197,  193,  198,
      224,  224,   55,  198,  199,  200,  198,  201,  198,  198,
      200,  200,  202,  198,  198,  198,  198,  198,  198,  198,
      200,  203,  198,  204,  224,  224,   55,  204,  205,  206,
      204,  207,  204,  204,  206,  206,  208,  204,  204,  204,
      204,  204,  204,  204,  206,  209,  204,  175,  123,  224,
      224,  224,  224,  123,  123,  176,  224,  224,  224,  224,
      224,  224,  224,  123,  177,  179,  128,  224,  224,  224,

      224,  128,  128,  180,  224,  224,  224,  224,  224,  224,
      224,  128,  181,   22,  182,  183,  224,  224,  224,  224,
      224,  224,  224,  184,   22,  182,  183,  224,  224,  224,
      224,  224,  224,  224,  184,  224,  224,  224,  224,  224,
      224,  213,   22,  185,  186,  224,  224,  224,  224,  224,
      224,  224,  187,   22,  185,  186,  224,  224,  224,  224,
      224,  224,  224,  187,   22,  185,  186,  224,  224,  224,
      224,  224,  224,  224,  187,  224,  224,  224,  224,  224,
      224,  214,   55,  224,  215,  224,  224,  216,  224,  224,
      224,  224,  217,   55,  224,  218,  224,  224,  219,  224,

      224,  224,  224,  220,   55,  224,  215,  224,  224,  216,
      224,  224,  224,  224,  217,  224,  224,  224,  224,  224,
      224,  222,   55,  224,  218,  224,  224,  219,  224,  224,
      224,  224,  220,   55,  224,  218,  224,  224,  219,  224,
      224,  224,  224,  220,  224,  224,  224,  224,  224,  224,
      223,   21,  224,  224,   21,   22,  224,  224,   22,   25,
      224,  224,   25,   49,  224,  224,   49,   54,  224,  224,
       54,   74,  224,  224,   74,   52,  224,  224,   52,   55,
      224,  224,   55,   85,  224,  224,   85,  111,  224,  224,
      111,  116,  224,  224,  116,  148,  224,  224,  148,  154,

      224,  224,  154,  200,  224,  224,  200,  206,  224,  224,
      206,  221,  221,  224,  221,    3,  224,  224,  224,  224,
      224,  224,  224,  224,  224,  224,  224,  224,  224,  224,
      224,  224,  224,  224,  224,  224,  224,  224,  224,  224
    } ;

static const flex_int16_t yy_chk[1441] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    4,    4,    9,   11,   15,   14,
        4,    4,    4,   14,    9,   11,   15,   18,   19,   27,
        4,    7,    7,    7,    7,   18,   19,   27,   29,    7,
        7,    7,  255,   31,   27,   32,   29,   33,   33,    7,
        8,   31,    8,   32,   36,   33,   38,  254,    8,   66,
       59,   60,   36,   38,   66,    8,   10,   10,   59,   60,
       64,  253,   10,   10,   10,   59,  173,   98,   64,   98,
      123,  128,   10,   12,   12,  173,  252,  169,  123,  128,

       12,   12,   13,   13,  131,  169,  170,  131,   13,   13,
       13,  251,  169,  171,  170,  250,  172,  249,   13,   16,
       16,  171,  248,   16,  172,   16,   16,   16,  171,  247,
      244,  243,  242,  237,  236,   16,   20,   20,  235,  234,
      229,  228,   20,   20,   20,  227,  225,  223,  222,  220,
      219,  216,   20,   21,   21,   21,   21,  214,  213,  211,
      210,   21,   21,   21,  187,  135,  134,  133,  120,  115,
       93,   21,   25,   25,   25,   92,   91,   88,   87,   83,
       82,   81,   25,   26,   26,   26,   26,   69,   57,   55,
       51,   26,   26,   26,   44,   40,   35,   24,   22,   17,

        3,   26,   28,    2,   28,    0,    0,   28,    0,    0,
        0,    0,   28,   30,   30,    0,    0,    0,    0,   30,
       30,   30,    0,    0,    0,    0,    0,    0,    0,   30,
       39,   39,    0,    0,    0,    0,   39,   39,   39,    0,
        0,    0,    0,    0,    0,    0,   39,   42,   42,    0,
        0,    0,    0,   42,   42,   42,    0,    0,    0,    0,
        0,    0,    0,   42,   43,   43,    0,    0,    0,    0,
       43,   43,   43,    0,    0,    0,    0,    0,    0,    0,
       43,   45,   45,   45,   45,    0,    0,    0,    0,   45,
       45,   45,    0,    0,    0,    0,    0,    0,    0,   45,

       46,   46,   46,    0,    0,    0,    0,    0,    0,    0,
       46,   47,   47,   47,    0,    0,    0,    0,    0,    0,
        0,   47,    0,    0,    0,    0,    0,    0,   47,   48,
       48,   48,    0,    0,    0,    0,    0,    0,    0,   48,
       49,   49,   49,   49,    0,    0,    0,    0,   49,   49,
       49,    0,    0,    0,    0,    0,    0,    0,   49,   52,
       52,   52,    0,    0,    0,    0,    0,    0,    0,   52,
       54,    0,   54,    0,    0,   54,    0,    0,    0,    0,
       54,   56,    0,   56,    0,    0,   56,    0,    0,    0,
        0,   56,    0,    0,    0,    0,    0,    0,   56,   58,

        0,   58,    0,    0,   58,    0,    0,    0,    0,   58,
       61,   61,    0,    0,    0,    0,   61,   61,   61,    0,
        0,    0,    0,    0,    0,    0,   61,   61,   63,   63,
        0,    0,    0,    0,   63,   63,   63,    0,    0,    0,
        0,    0,    0,    0,   63,   63,   65,   65,    0,    0,
        0,    0,   65,   65,   65,    0,    0,    0,    0,    0,
        0,    0,   65,   67,   67,    0,    0,    0,    0,   67,
       67,   67,    0,    0,    0,    0,    0,    0,    0,   67,
       68,   68,    0,    0,    0,    0,   68,   68,   68,    0,
        0,    0,    0,    0,    0,    0,   68,   71,   71,    0,

        0,    0,    0,   71,   71,   71,    0,    0,    0,    0,
        0,    0,    0,   71,   71,   73,   73,    0,    0,    0,
        0,   73,   73,   73,    0,    0,    0,    0,    0,    0,
        0,   73,   73,   74,   74,   74,   74,    0,    0,    0,
        0,   74,   74,   74,    0,    0,    0,    0,    0,    0,
        0,   74,   74,   77,    0,    0,   77,   77,   77,   77,
       77,   77,   77,   77,   77,   77,   77,   77,   77,   77,
       77,   77,   77,   77,   77,   77,   77,   78,   78,   78,
       78,    0,    0,    0,    0,   78,   78,   78,    0,    0,
        0,    0,    0,    0,    0,   78,   79,   79,   79,    0,

        0,    0,    0,    0,    0,    0,   79,   80,   80,   80,
        0,    0,    0,    0,    0,    0,    0,   80,    0,    0,
        0,    0,    0,    0,   80,   84,    0,   84,   84,    0,
       84,    0,    0,   84,   84,   84,    0,    0,    0,    0,
        0,    0,    0,   84,   85,    0,   85,    0,    0,   85,
        0,    0,    0,    0,   85,   86,    0,   86,    0,    0,
       86,    0,    0,    0,    0,   86,    0,    0,    0,    0,
        0,    0,   86,   89,   89,    0,    0,    0,    0,   89,
       89,   89,    0,    0,    0,    0,    0,    0,    0,   89,
       90,   90,    0,    0,    0,    0,   90,   90,   90,    0,

        0,    0,    0,    0,    0,    0,   90,   90,   94,   94,
        0,    0,    0,    0,   94,   94,   94,    0,    0,    0,
        0,    0,    0,    0,   94,   94,   99,   99,    0,    0,
        0,    0,   99,   99,   99,    0,    0,    0,    0,    0,
        0,    0,   99,   99,  101,  101,    0,    0,    0,    0,
      101,  101,  101,    0,    0,    0,    0,    0,    0,    0,
      101,  101,  102,  102,    0,    0,    0,    0,  102,  102,
      102,    0,    0,    0,    0,    0,    0,    0,  102,  103,
      103,    0,    0,    0,    0,  103,  103,  103,    0,    0,
        0,    0,    0,    0,    0,  103,  103,  104,  104,    0,

        0,    0,    0,  104,  104,  104,    0,    0,    0,    0,
        0,    0,    0,  104,  104,  105,    0,    0,  105,  105,
      105,  105,  105,  105,  105,  105,  105,  105,  105,  105,
      105,  105,  105,  105,  105,  105,  105,  105,  105,  110,
        0,    0,  110,  110,  110,  110,  110,  110,  110,  110,
      110,  110,  110,  110,  110,  110,  110,  110,  110,  110,
      110,  110,  110,  111,  111,  111,  111,    0,    0,    0,
        0,  111,  111,  111,    0,    0,    0,    0,    0,    0,
        0,  111,  111,  114,    0,    0,  114,  114,  114,  114,
      114,  114,  114,  114,  114,  114,  114,  114,  114,  114,

      114,  114,  114,  114,  114,  114,  114,  116,    0,  116,
      116,    0,  116,    0,    0,  116,  116,  116,    0,    0,
        0,    0,    0,    0,    0,  116,  116,  119,    0,    0,
      119,  119,  119,  119,  119,  119,  119,  119,  119,  119,
      119,  119,  119,  119,  119,  119,  119,  119,  119,  119,
      119,  121,  121,    0,    0,    0,    0,  121,  121,  121,
        0,    0,    0,    0,    0,    0,    0,  121,  121,  124,
      124,    0,    0,    0,    0,  124,  124,  124,    0,    0,
        0,    0,    0,    0,    0,  124,  124,  132,  132,    0,
        0,    0,    0,  132,  132,  132,    0,    0,    0,    0,

        0,    0,    0,  132,  132,  136,  136,    0,    0,    0,
        0,  136,  136,  136,    0,    0,    0,    0,    0,    0,
        0,  136,  136,  137,  137,    0,    0,    0,    0,  137,
      137,  137,    0,    0,    0,    0,    0,    0,    0,  137,
      137,  139,  139,    0,    0,    0,    0,  139,  139,  139,
        0,    0,    0,    0,    0,    0,    0,  139,  139,  148,
      148,  148,    0,    0,    0,    0,    0,    0,    0,  148,
      154,  154,  154,    0,    0,    0,    0,    0,    0,    0,
      154,  157,    0,    0,  157,  157,  157,  157,  157,  157,
      157,  157,  157,  157,  157,  157,  157,  157,  157,  157,

      157,  157,  157,  157,  157,  162,    0,    0,  162,  162,
      162,  162,  162,  162,  162,  162,  162,  162,  162,  162,
      162,  162,  162,  162,  162,  162,  162,  162,  162,  163,
        0,    0,  163,  163,  163,  163,  163,  163,  163,  163,
      163,  163,  163,  163,  163,  163,  163,  163,  163,  163,
      163,  163,  163,  168,    0,    0,  168,  168,  168,  168,
      168,  168,  168,  168,  168,  168,  168,  168,  168,  168,
      168,  168,  168,  168,  168,  168,  168,  174,  174,    0,
        0,    0,    0,  174,  174,  174,    0,    0,    0,    0,
        0,    0,    0,  174,  174,  176,  176,    0,    0,    0,

        0,  176,  176,  176,    0,    0,    0,    0,    0,    0,
        0,  176,  176,  182,  182,  182,    0,    0,    0,    0,
        0,    0,    0,  182,  183,  183,  183,    0,    0,    0,
        0,    0,    0,    0,  183,    0,    0,    0,    0,    0,
        0,  183,  184,  184,  184,    0,    0,    0,    0,    0,
        0,    0,  184,  185,  185,  185,    0,    0,    0,    0,
        0,    0,    0,  185,  186,  186,  186,    0,    0,    0,
        0,    0,    0,    0,  186,    0,    0,    0,    0,    0,
        0,  186,  200,    0,  200,    0,    0,  200,    0,    0,
        0,    0,  200,  206,    0,  206,    0,    0,  206,    0,

        0,    0,    0,  206,  215,    0,  215,    0,    0,  215,
        0,    0,    0,    0,  215,    0,    0,    0,    0,    0,
        0,  215,  217,    0,  217,    0,    0,  217,    0,    0,
        0,    0,  217,  218,    0,  218,    0,    0,  218,    0,
        0,    0,    0,  218,    0,    0,    0,    0,    0,    0,
      218,  226,    0,    0,  226,  230,    0,    0,  230,  231,
        0,    0,  231,  232,    0,    0,  232,  233,    0,    0,
      233,  238,    0,    0,  238,  239,    0,    0,  239,  240,
        0,    0,  240,  241,    0,    0,  241,  245,    0,    0,
      245,  246,    0,    0,  246,  256,    0,    0,  256,  257,

        0,    0,  257,  258,    0,    0,  258,  259,    0,    0,
      259,  260,  260,    0,  260,  224,  224,  224,  224,  224,
      224,  224,  224,  224,  224,  224,  224,  224,  224,  224,
      224,  224,  224,  224,  224,  224,  224,  224,  224,  224
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[19] =
    {   0,
1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#ifndef YYLMAX
#define YYLMAX 8192
#endif

char yytext[YYLMAX];
char *yytext_ptr;
#line 1 "shell.l"
/*
 *
 * CS-252 
 * shell.l: lexical analyzer for shell
 * You have to extend it.
 *
 */
#line 11 "shell.l"

#include <cstring>
#include <string.h>
#include <unistd.h>
#include <sys/wait.h>
#include <stdio.h>

#include "y.tab.hh"

static void yyunput (int c, char *buf_ptr);

void myunputc(int c) {
  unput(c);
}

#line 889 "lex.yy.cc"
#line 890 "lex.yy.cc"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 30 "shell.l"


#line 1113 "lex.yy.cc"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 225 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1416 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 32 "shell.l"
{
  return NEWLINE;
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 36 "shell.l"
{
  /* Discard spaces and tabs */
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 40 "shell.l"
{
  return AMPERSAND;
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 44 "shell.l"
{
  return GREAT;
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 48 "shell.l"
{
  return GREATGREAT;
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 52 "shell.l"
{
  return GREATAMPERSAND;
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 56 "shell.l"
{
  return TWOGREAT;
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 60 "shell.l"
{
  return GREATGREATAMPERSAND;
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 64 "shell.l"
{
  return LESS;
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 68 "shell.l"
{
  return PIPE;
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 72 "shell.l"
{
  /* string contains quotes */
  int size = strlen(yytext);
  int counter =  0;
  char yytext_trimed[size - 1];
  yytext_trimed[size - 2] = '\0';
  for (int i = 1; i < size - 1; i++) {
    yytext_trimed[counter] = yytext[i];
    counter++;
  }
  yylval.cpp_string = new std::string(yytext_trimed);
  return WORD;
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 86 "shell.l"
{
  /* string contains slash */
  int size = strlen(yytext);
  int counter = 0;
  int pos[10];
  int index = 0;
  for (int i = 0; i < size; i++) {
    if (yytext[i] == '\\') {
      pos[index] = i;
      index++;
      i++;
    }
  }
  char yytext_trimed[size - index + 1];
  yytext_trimed[size - index] = '\0';
  int index_2 = 0;
  for (int i = 0; i < size; i++) {
    if (i != pos[index_2]) {
      yytext_trimed[counter] = yytext[i];
      counter++;
    }
    else {
      index_2++;
    }
  }
  yylval.cpp_string = new std::string(yytext_trimed);
  return WORD;
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 115 "shell.l"
{
  /* subshell */
  // create two pipes
  int pin[2], pout[2];
  pipe(pin);   // pin: parent writes command, child reads and executes
  pipe(pout);  // pout: child sends output, parents reads and prints

  char* sub_command = new char[strlen(yytext) - 2];
  sub_command[strlen(sub_command) - 1] = '\0';

  int index = 0;
  for (int i = 2; i < strlen(yytext) - 1; i++) {
    sub_command[index] = yytext[i];
    index++;
  }

  write(pin[1], sub_command, strlen(sub_command) + 1);
  write(pin[1], "\n", 1);
  // write(pin[1], "exit\n", 6);
  close(pin[1]);

  // save stdin/stdout/stderr
  int tmpin = dup(0);
  int tmpout = dup(1);
  int tmperr = dup(2); 

  dup2(pin[0], 0);
  dup2(pout[1], 1);
  close(pin[0]);
  close(pout[1]);

  int ret = fork();
  if (ret == 0) {
    // child process
    const char** args = new const char*[2];
    args[1] = "proc/self/exe";
    args[2]  = NULL;

    // execute argument list
    execvp("/proc/self/exe", (char* const*) args);
    perror("execvp subshell");
    _exit(1);
  }
  else if (ret > 0) {
    // parent process
    // restore stdin/stdout/stderr
    dup2(tmpin, 0);
    dup2(tmpout, 1);
    dup2(tmperr, 2);
    close(tmpin);
    close(tmpout);
    close(tmperr);

    // read input from child process
    char* sub_result_char;
    char* sub_result = new char[1000];
    int counter = 0;
    while (read(pout[0], sub_result_char, 1)) {
      if (*sub_result_char == '\n' || *sub_result_char == '\t') {
        sub_result[counter++] = ' ';
      }
      else {
        sub_result[counter++] = *sub_result_char;
      }
    }
    sub_result[counter] = '\0';
    close(pout[0]);

    // write result to command line
    for (int i = strlen(sub_result) - 1; i >= 0; i--) {
      myunputc(sub_result[i]);
    }
  }
  else {
    // fork failed
    perror("fork subshell");
    exit(1);
  } 
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 195 "shell.l"
{
  /* source file */
  // get source file name
  char* filename = new char[strlen(yytext) - 6];
  filename[strlen(filename) - 1] = '\0';
  int index = 0;
  for (int i = 7; i < strlen(yytext); i++) {
    filename[index++] = yytext[i];
  }

  // read content in source file
  char* line = NULL;
  size_t length = 0;
  FILE* file = fopen(filename, "r");
  if (file == NULL) {
    perror("fopen");
    exit(1);
  }
  while (true) {
    ssize_t char_count = getline(&line, &length, file);
    if (char_count != -1) {
      // unput line in source file to shell
      for (int i = (int)(strlen(line) - 1); i >= 0; i--) {
        myunputc(line[i]);
      }
      myunputc('\n');
    }
    else {
      break;
    }
  }

  fclose(file);
  free(line);
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 231 "shell.l"
{
  /* environ var expansion */
  // get environ var name
  int index = 0;
  int env_num = 0;
  while (yytext[index] != '\0') {
    if (yytext[index] == '$') {
      env_num++;
      index += 2;
    }
    index++;
  }

  index = 0;
  int* start_indices = new int[env_num];
  int* end_indices = new int[env_num];
  int counter = 0;
  while (yytext[index] != '\0') {
    if (yytext[index] == '{') {
      start_indices[counter] = index + 1;
    }
    else if (yytext[index] == '}') {
      end_indices[counter++] = index - 1;
    }
    index++;
  }

  char** env_names = new char*[env_num];
  for (int i = 0; i < env_num; i++) {
    env_names[i] = new char[end_indices[i] - start_indices[i] + 2];
    env_names[i][end_indices[i] - start_indices[i] + 1] = '\0';
    for (int j = 0; j < end_indices[i] - start_indices[i] + 1; j++) {
      env_names[i][j] = yytext[start_indices[i] + j];
    }
  }

  // get content in environ var
  char** env_strs = new char*[env_num];
  for (int i = 0; i < env_num; i++) {
    if (!strcmp(env_names[i], "$")) {
      env_strs[i] = new char[10];
      pid_t pid = getpid();
      sprintf(env_strs[i], "%d", pid);
    }
    else if (!strcmp(env_names[i], "?")) {
      printf("?\n");
    }
    else if (!strcmp(env_names[i], "!")) {
      printf("?\n");
    }
    else if (!strcmp(env_names[i], "_")) {
      printf("?\n");
    }
    else if (!strcmp(env_names[i], "SHELL")) {
      printf("?\n");
    }
    else {
      env_strs[i] = getenv(env_names[i]);
    }
    // printf("%s\n", env_strs[i]);
  }

  char** others = new char*[env_num + 1];
  int ctr = 0;
  for (int i = 0; i < env_num + 1; i++) {
    if (i == 0) {
      if (start_indices[i] == 2) {
        others[i] = NULL;
      }
      else {
        others[i] = new char[start_indices[i] - 1];
        others[i][start_indices[i] - 2] = '\0';
        for (int j = 0; j < start_indices[i] - 2; j++) {
          others[i][ctr++] = yytext[j];
        }
      }
    }
    else if (i == env_num) {
      if (end_indices[i - 1] == strlen(yytext) - 2) {
        others[i] = NULL;
      }
      else {
        others[i] = new char[strlen(yytext) - end_indices[i - 1] - 2];
        others[i][end_indices[i - 1] - 2] = '\0';
        for (int j = end_indices[i - 1] + 2; j < strlen(yytext); j++) {
          others[i][ctr++] = yytext[j];
        }
      }
    }
    else {
      if (end_indices[i - 1] == (start_indices[i] - 4)) {
        others[i] = NULL;
      }
      else {
        others[i] = new char[start_indices[i] - end_indices[i - 1] - 3];
        others[i][start_indices[i] - end_indices[i - 1] - 2] = '\0';
        for (int j = end_indices[i - 1] + 2; j < start_indices[i] - 2; j++) {
          others[i][ctr++] = yytext[j];
        }
      }
    }
    ctr = 0;
  }

  // concat everything to final result
  char* result = new char[1000];
  for (int i = 0; i < env_num; i++) {
    if (i == 0) {
      if (others[i] != NULL) {
        strcpy(result, others[i]);
      }
    }
    strcat(result, env_strs[i]);
    if (others[i + 1] != NULL) {
      strcat(result, others[i + 1]);
    }
  }

  strcat(result, "wrong");
  // printf("%s\n", result);
  yylval.cpp_string = new std::string(result);
  return WORD;
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 355 "shell.l"
{
  yylval.cpp_string = new std::string(getenv("HOME"));
  return WORD;
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 360 "shell.l"
{
  /* Assume that file names have only alpha chars */
  yylval.cpp_string = new std::string(yytext);
  return WORD;
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 365 "shell.l"
ECHO;
	YY_BREAK
#line 1572 "lex.yy.cc"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 225 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 225 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 224);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');
	if ( YY_CURRENT_BUFFER_LVALUE->yy_at_bol )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 365 "shell.l"
